# Generated by Django 3.1.2 on 2020-11-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dealers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealers',
        ),
    ]
