# Generated by Django 3.1.2 on 2020-11-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('newprice', models.FloatField()),
                ('product_type', models.CharField(max_length=300)),
                ('stock', models.IntegerField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagefull_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagefull_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagefull_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagefull_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.dealers')),
            ],
        ),
    ]
