# Generated by Django 3.1.2 on 2020-11-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='product_image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagefull_1',
            new_name='product_image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagefull_2',
            new_name='product_image3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imagefull_3',
            new_name='product_image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagefull_4',
        ),
    ]
