# Generated by Django 3.1.2 on 2020-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_auto_20201108_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
