# Generated by Django 3.1.2 on 2020-11-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_auto_20201108_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.FileField(max_length=2555, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.product'),
        ),
    ]
