# Generated by Django 3.1.2 on 2020-11-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
        ('dealer', '0009_auto_20201110_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.dealers'),
        ),
    ]
