# Generated by Django 3.1.2 on 2020-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_order_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, max_length=2555, null=True, upload_to='product/images'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.FileField(max_length=2555, upload_to='product/images'),
        ),
    ]
