# Generated by Django 3.1.2 on 2020-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_auto_20201110_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
