# Generated by Django 3.1.2 on 2020-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_order_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
