# Generated by Django 3.1.2 on 2020-11-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0014_auto_20201112_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='payment_cod',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='payment_status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
