# Generated by Django 2.0.2 on 2020-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0015_auto_20201114_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
