# Generated by Django 2.0.2 on 2020-11-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0016_auto_20201115_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
