# Generated by Django 2.0.2 on 2020-11-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0018_auto_20201118_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.FileField(blank=True, max_length=2555, null=True, upload_to='offer')),
                ('offer_name', models.CharField(max_length=220, null=True)),
                ('discount_amount', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='newprice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Product'),
        ),
    ]
