# Generated by Django 2.0.2 on 2020-11-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0019_auto_20201119_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.Product'),
        ),
    ]
