# Generated by Django 2.0.2 on 2020-11-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0020_auto_20201119_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_product',
            new_name='product',
        ),
    ]
