# Generated by Django 2.0.2 on 2020-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0022_offer_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_sart',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
