# Generated by Django 2.0.2 on 2020-11-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0023_auto_20201119_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_sart',
            new_name='offer_start',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
