# Generated by Django 2.0.2 on 2020-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0025_product_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
