# Generated by Django 2.0.2 on 2020-11-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_catogeries'),
        ('dealer', '0026_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='catogery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.catogeries'),
        ),
    ]
