# Generated by Django 2.0.2 on 2020-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0027_offer_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reff_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='refferd_user',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
