# Generated by Django 2.0.2 on 2020-11-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0029_auto_20201121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
