# Generated by Django 2.0.2 on 2020-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0030_auto_20201124_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
