# Generated by Django 3.1.2 on 2020-11-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0031_auto_20201124_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
