# Generated by Django 3.1.2 on 2020-11-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0032_auto_20201127_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='profile_photos'),
        ),
    ]
