# Generated by Django 3.1.2 on 2020-11-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catogeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=225, null=True)),
                ('image', models.FileField(max_length=2555, upload_to='catogeries/images')),
            ],
        ),
    ]
