# Generated by Django 3.1.2 on 2020-11-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_catogeries'),
    ]

    operations = [
        migrations.CreateModel(
            name='reffreal_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reff_name', models.CharField(max_length=225, null=True)),
                ('reff_discount', models.IntegerField(max_length=225, null=True)),
                ('refferd_person_discount', models.IntegerField(max_length=225, null=True)),
                ('reff_status', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
