# Generated by Django 3.1.2 on 2020-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_auto_20201128_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='reffreal_offer',
            name='order_maximum',
            field=models.IntegerField(null=True),
        ),
    ]
