# Generated by Django 3.1.2 on 2020-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_reffreal_offer_order_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='reffreal_offer',
            name='reff_price',
            field=models.IntegerField(null=True),
        ),
    ]
