# Generated by Django 3.1.2 on 2020-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_reffreal_offer_reff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reffreal_offer',
            name='reff_offer_type',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
